[
  {
    "cmd": [
      "rdb",
      "stream",
      "-var",
      "builder:test_buildername",
      "-var",
      "test_suite:script_test",
      "-tag",
      "step_name:script_test",
      "-tag",
      "target_platform:linux",
      "-coerce-negative-duration",
      "-new",
      "-realm",
      "chromium:ci",
      "-include",
      "-exonerate-unexpected-pass",
      "--",
      "vpython3",
      "None/testing/scripts/script.py",
      "--build-config-fs",
      "Release",
      "--paths",
      "{\"checkout\": \"None\"}",
      "--properties",
      "{\"bot_id\": \"fake-bot-id\", \"buildername\": \"test_buildername\", \"buildnumber\": 571, \"mastername\": \"test_group\", \"slavename\": \"fake-bot-id\", \"target_platform\": \"linux\"}",
      "--args",
      "[\"some\", \"args\"]",
      "run",
      "--output",
      "/path/to/tmp/json"
    ],
    "luci_context": {
      "realm": {
        "name": "chromium:ci"
      },
      "resultdb": {
        "current_invocation": {
          "name": "invocations/build:8945511751514863184",
          "update_token": "token"
        },
        "hostname": "rdbhost"
      }
    },
    "name": "script_test",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@json.output@{}@@@",
      "@@@STEP_LOG_END@json.output@@@",
      "@@@STEP_LOG_END@raw_io.output_text[stderr]@@@"
    ]
  },
  {
    "cmd": [],
    "name": "script_test with suffix  had an invalid result",
    "~followup_annotations": [
      "@@@STEP_TEXT@The recipe expected the result to contain the key 'failures'. Contents are:<br/>{}@@@",
      "@@@STEP_FAILURE@@@"
    ]
  },
  {
    "cmd": [],
    "name": "details",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@details@compile_targets: ['compile_target']@@@",
      "@@@STEP_LOG_LINE@details@uses_local_devices: False@@@",
      "@@@STEP_LOG_END@details@@@"
    ]
  },
  {
    "failure": {
      "failure": {},
      "humanReason": "Step('script_test with suffix  had an invalid result') (retcode: 0)"
    },
    "name": "$result"
  }
]